version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: revike
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: todo

  backend:
    build:
      context: .
    expose:
      - 8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && gunicorn todo.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      - db

  nginx:
    build: todo/nginx
    ports:
    - 8000:80
    depends_on:
      - backend

  frontend:
    build: todo/frontend
    ports:
    - 8002:80
    depends_on:
      - nginx
