# Generated by Django 3.2.3 on 2021-05-29 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_todouser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todouser',
            name='group',
        ),
    ]
