# Generated by Django 3.2 on 2021-05-21 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='название проекта')),
                ('link', models.CharField(max_length=128, verbose_name='ссылка на репоз-й')),
                ('users', models.ManyToManyField(to='users.ToDoUser', verbose_name='пользователи')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='текст заметки')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='создан')),
                ('date_update', models.DateField(auto_now=True, verbose_name='обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.todouser')),
            ],
        ),
    ]
